# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 07:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='pizza',
        ),
        migrations.AddField(
            model_name='pizza',
            name='ingredients',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Ingredient'),
        ),
    ]
