# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170702_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='prix',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
