# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170702_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='app.Ingredient'),
        ),
    ]
