# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 08:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170702_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='description',
        ),
    ]
