# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 09:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_pizza_categorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, default=None, max_length=10)),
                ('prenom', models.CharField(blank=True, default=None, max_length=10)),
                ('mail', models.EmailField(blank=True, default=None, max_length=20)),
                ('adresse1', models.CharField(blank=True, default=None, max_length=40)),
                ('adresse2', models.CharField(blank=True, default=None, max_length=40)),
                ('cp', models.CharField(blank=True, default=None, max_length=5)),
                ('ville', models.CharField(blank=True, default=None, max_length=20)),
                ('telephone', models.CharField(blank=True, default=None, max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
