# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_personne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='mail',
            field=models.EmailField(blank=True, default=None, max_length=50),
        ),
    ]
