# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_panier_panierdetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PanierDetails',
            new_name='PanierDetail',
        ),
    ]
