# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 07:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0010_auto_20170703_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(blank=True, default=None, max_length=20)),
                ('nom', models.CharField(blank=True, default=None, max_length=15)),
                ('mail', models.EmailField(blank=True, default=None, max_length=50)),
                ('adresse1', models.CharField(blank=True, default=None, max_length=40)),
                ('adresse2', models.CharField(blank=True, default=None, max_length=40)),
                ('cp', models.CharField(blank=True, default=None, max_length=5)),
                ('ville', models.CharField(blank=True, default=None, max_length=20)),
                ('telephone', models.CharField(blank=True, default=None, max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='panierdetail',
            name='panier',
        ),
        migrations.RemoveField(
            model_name='panierdetail',
            name='pizza',
        ),
        migrations.AddField(
            model_name='panier',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='panier',
            name='id_paiement',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='panier',
            name='date_creation',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='panier',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='PanierDetail',
        ),
        migrations.AddField(
            model_name='commande',
            name='panier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Panier'),
        ),
        migrations.AddField(
            model_name='commande',
            name='pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Pizza'),
        ),
    ]
